services:
  lets-encrypt:
    image: kouleen/lets-encrypt:latest
    container_name: lets-encrypt
    ports:
      - "8099:8099"
    environment:
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SEND_EMAIL=${SEND_EMAIL}
      - SEND_PWD=${SEND_PWD}
    volumes:
      - /usr/bin/docker:/usr/bin/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/nginx/certs:/app/nginx/certs
    networks:
      - lets-encrypt-network
networks:
  lets-encrypt-network:
    driver: bridge
    name: lets-encrypt-network
